// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqhmnzdvmtrelwghzwbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxaG1uemR2bXRyZWx3Z2h6d2JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyMzcwOTQsImV4cCI6MjA3ODgxMzA5NH0.yHqXsU7g93HOqSMNRzzKkrS5_C0d1WU1vni0XanGxeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});